version: 2

sources:
  - name: clientes_bronze
    schema: clientes
    tables:
      - name: bronze
  - name: vendas_bronze
    schema: vendas
    tables:
      - name: bronze

models:
  - name: cl_clientes
    description: "Tabela de clientes enriquecida e limpa."
    columns:
      - name: cliente_id
        description: "Chave primária do cliente."
        tests:
          - unique
          - not_null
      - name: nome
        description: "Nome do cliente."
      - name: email
        description: "Email do cliente."
        tests:
          - unique
          - not_null
      - name: status
        description: "Status do cliente."
        tests:
          - accepted_values:
              arguments:
                values: ['ativo', 'inativo', 'pendente']

  - name: ft_vendas
    description: "Tabela de vendas enriquecida e limpa."
    columns:
      - name: venda_id
        description: "Chave primária da venda."
        tests:
          - unique
          - not_null
      - name: cliente_id
        description: "Chave estrangeira para a tabela de clientes."
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('cl_clientes')
                field: cliente_id
      - name: data_venda
        description: "Data em que a venda ocorreu."
      - name: valor_total
        description: "Valor total da venda."
