apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: datalake
servers: 1
agents: 2
ports:
  - port: "5432:5432"
  - port: "9000:9000"
  - port: "9001:9001"
  - port: "8080:8080"
  - port: "7077:7077"
  - port: "8081:8081"
  - port: "18080:18080"
  - port: "8085:8080"
volumes: []