# k3d-datalake.yaml
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: datalake
servers: 1
agents: 3 # 3 agents to allow for Spark executor scaling demonstrations
kubeAPI:
  hostPort: "6443"
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: local-registry
    host: "0.0.0.0"
    hostPort: "5000"
  config: |
    mirror:
      endpoint:
        - http://local-registry:5000
