# infra/kubernetes/10-postgres.yaml
# Define os recursos principais para o serviço do PostgreSQL.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce # O volume só pode ser montado por um nó por vez.
  resources:
    requests:
      storage: 5Gi # Aloca 5Gi de espaço para o banco de dados.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:14 # Usar uma tag de imagem específica.
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          # Monta as credenciais do banco de dados a partir do nosso Secret.
          # Isso evita hard-coding de senhas no deployment.
          envFrom:
            - secretRef:
                name: postgres-credentials
          # Monta o volume persistente onde os dados serão armazenados.
          volumeMounts:
            - name: postgres-storage
              mountPath: /bitnami/postgresql
            # Monta o script de inicialização no diretório que o Bitnami executa.
            - name: postgres-init-script-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-init-script-volume
          configMap:
            name: postgres-init-script

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
spec:
  type: ClusterIP # Expõe o serviço apenas dentro do cluster.
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
