# infra/kubernetes/21-airflow-deployment.yaml
# Define os recursos para o Airflow (LocalExecutor).

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Volume para logs e para o banco de dados SQLite.

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  type: ClusterIP
  selector:
    app: airflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      # Usa a ServiceAccount que criamos com permissões para o Spark Operator.
      serviceAccountName: airflow-sa
      containers:
        - name: airflow
          image: pyspark-lakehouse-airflow:latest
          imagePullPolicy: IfNotPresent
          # Comando para inicializar o DB, e rodar scheduler e webserver.
          command:
            - "bash"
            - "-c"
            - "airflow db init && airflow scheduler & airflow webserver"
          env:
            # Aponta para o arquivo do SQLite no volume persistente.
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: "sqlite:////opt/airflow/logs/airflow.db"
            - name: AIRFLOW__CORE__EXECUTOR
              value: "LocalExecutor"
            # Define as credenciais do Postgres e MinIO como variáveis de ambiente.
            - name: POSTGRES_HOST
              value: "postgres.postgres.svc.cluster.local"
            - name: MINIO_ENDPOINT
              value: "http://minio.minio.svc:9000"
          # Monta os secrets com as senhas.
          envFrom:
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: minio-credentials
          ports:
            - name: web
              containerPort: 8080
          # Monta o volume para logs e o banco de dados.
          volumeMounts:
            - name: airflow-logs-storage
              mountPath: /opt/airflow/logs
      volumes:
        - name: airflow-logs-storage
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
