helmDefaults:
  timeout: 1200
  wait: true
  waitForJobs: true
  atomic: true
  recreatePods: false

repositories:
  - name: airflow
    url: https://airflow.apache.org

releases:
  - name: airflow
    namespace: airflow
    createNamespace: true

    chart: airflow/airflow
    version: "1.19.x"

    values:
      - airflowVersion: "2.9.3"
      - executor: "LocalExecutor"

      - config:
          core:
            load_examples: "false"
          logging:
            remote_logging: "False"

      - postgresql:
          enabled: false

      - data:
          metadataConnection:
            protocol: postgresql
            host: postgres
            port: 5432
            user: admin
            pass: admin
            db: origem_db

      - dags:
          persistence:
            enabled: true
            size: 2Gi

      - logs:
          persistence:
            enabled: false

      - env:
          - name: AIRFLOW_CONN_POSTGRES_DEFAULT
            value: postgresql://admin:admin@postgres:5432/origem_db

          - name: AIRFLOW_CONN_SPARK_DEFAULT
            value: spark://spark-master:7077

          - name: MINIO_ENDPOINT
            value: http://minio:9000

          - name: MINIO_ACCESS_KEY
            value: admin

          - name: MINIO_SECRET_KEY
            value: admin123

          - name: MINIO_BUCKET
            value: datalake

      - webserver:
          defaultUser:
            enabled: true
            username: admin
            password: admin
            email: admin@example.com
            firstName: Admin
            lastName: User

      - scheduler:
          replicas: 1

      - workers:
          replicas: 0

      - triggerer:
          enabled: false

      - migrations:
          waitTimeout: 600

      - service:
          type: NodePort
          ports:
            - name: web
              port: 8080
              targetPort: 8080
              nodePort: 30085