apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: cluster

servers: 1
agents: 3

kubeAPI:
  hostPort: "6443"

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer

registries:
  create:
    name: local-registry
    host: "0.0.0.0"
    hostPort: "5000"
  config: |
    mirrors:
      "docker.io":
        endpoint:
          - http://local-registry:5000

volumes:
  - volume: /tmp/k3d-storage:/var/lib/rancher/k3s/storage
    nodeFilters:
      - all

options:
  k3s:
    extraArgs:
      - arg: --kubelet-arg=eviction-hard=imagefs.available<1%,nodefs.available<1%,ephemeral-storage<1%
        nodeFilters: [ "all" ]
      - arg: --kubelet-arg=eviction-minimum-reclaim=imagefs.available=1%,nodefs.available=1%,ephemeral-storage=1%
        nodeFilters: [ "all" ]
      - arg: --kubelet-arg=eviction-soft=imagefs.available<5%,nodefs.available<5%,ephemeral-storage<5%
        nodeFilters: [ "all" ]
      - arg: --node-taint=node-role.kubernetes.io/control-plane=
        nodeFilters: [ "server:*" ]