apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
# airflow-scripts-pvc.yaml (compartilhado dags/scripts)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-scripts-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi