version: 2

models:
  - name: datamart_resumo_vendas_cliente
    description: "Tabela denormalizada para análise de vendas por cliente."
    columns:
      - name: venda_id
        description: "Chave primária da venda."
        tests:
          - unique
          - not_null
      - name: cliente_id
        description: "Chave do cliente."
        tests:
          - not_null
      - name: cliente_nome
        description: "Nome do cliente."
      - name: cliente_cidade
        description: "Cidade do cliente."
      - name: cliente_estado
        description: "Estado do cliente."
      - name: data_venda
        description: "Data da venda."
      - name: valor_total
        description: "Valor total da venda."