apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-silver-transform
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "localhost:5000/pyspark-basic-spark:latest"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///opt/spark/work-dir/spark_jobs/silver/clean_dedup.py"
  sparkVersion: "3.5"
  restartPolicy:
    type: Never
  
  deps:
    packages:
      - "io.delta:delta-spark_2.12:3.1.0"

  dynamicAllocation:
    enabled: true
    initialExecutors: 1
    minExecutors: 1
    maxExecutors: 10
    shuffleTrackingTimeout: 60

  sparkConf:
    spark.ui.port: "4040"
    spark.hadoop.fs.s3a.endpoint: "http://minio.minio.svc.cluster.local:9000"
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.connection.ssl.enabled: "false"
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "s3a://spark-logs/"

  driver:
    cores: 1
    memory: "1024m"
    labels:
      version: 3.5.0
    serviceAccount: spark
    envFrom:
      - secretRef:
          name: minio-credentials

  executor:
    cores: 1
    instances: 1
    memory: "1024m"
    labels:
      version: 3.5.0
    envFrom:
      - secretRef:
          name: minio-credentials
