# infra/kubernetes/values/airflow-values.yaml

# Configurações da imagem Docker a ser usada para todos os componentes do Airflow.
images:
  airflow:
    repository: "pyspark-lakehouse-airflow"
    tag: "latest"
    pullPolicy: "IfNotPresent"

# Define o executor para KubernetesExecutor.
executor: "KubernetesExecutor"

# Deploy do PostgreSQL para o metadata database do Airflow.
postgresql:
  enabled: true
  auth:
    username: "airflow"
    password: "airflow-password"
    database: "airflow-metastore"

# As DAGs estão na imagem Docker, então o git-sync é desativado.
dags:
  persistence:
    enabled: false
  gitSync:
    enabled: false

# Persistência para os logs das tasks do Airflow.
logs:
  persistence:
    enabled: true
    size: 5Gi

# Configurações do Webserver.
webserver:
  defaultUser:
    enabled: true
    role: "Admin"
    username: "admin"
    password: "admin"
  service:
    type: ClusterIP
    ports:
      - name: webserver
        port: 8080

# Monta secrets existentes como variáveis de ambiente em todos os componentes.
# A sintaxe correta usa o pipe (|) para tratar o bloco como uma string multi-linha.
# Estes segredos serão montados no scheduler, webserver, e também nos pods
# de worker que o KubernetesExecutor irá criar.
extraEnvFrom: |
  - secretRef:
      name: "postgres-credentials-secret"
  - secretRef:
      name: "minio-credentials-secret"
