apiVersion: k3d.io/v1alpha5
kind: Simple
servers: 1
agents: 3
ports:
  - port: 8085:80       # Airflow UI
    nodeFilters:
      - loadbalancer
  - port: 9001:9001     # MinIO Console
    nodeFilters:
      - loadbalancer
  - port: 18080:18080   # Spark History Server
    nodeFilters:
      - loadbalancer
  - port: 5432:5432     # PostgreSQL
    nodeFilters:
      - loadbalancer